fix: lua version extraction

diff --git a/.github/actions/package-nfpm/action.yml b/.github/actions/package-nfpm/action.yml
--- a/.github/actions/package-nfpm/action.yml
+++ b/.github/actions/package-nfpm/action.yml
@@ -57,17 +57,21 @@ runs:
 
         if  [ "${{ inputs.package_extension }}" = "rpm" ]; then
           export DIST=".${{ inputs.distrib }}"
-          luaver=$(lua -e "print(string.sub(_VERSION, 5))" 2>/dev/null || echo 0)
         else
           export DIST=""
-          luaver=$(lua -e "print(string.match(_VERSION, '%d+.%d+'))" 2>/dev/null || echo 0)
+        fi
+
+        luaver=$(lua -e "print(string.sub(_VERSION, 5))" 2>/dev/null || echo 0)
+        echo "luaver is $luaver"
+        if [ $luaver = "0" ]; then
+          echo "Cannot get lua version"
+          exit 1
         fi
 
         export RPM_SIGNING_KEY_FILE="$(pwd)/key.gpg"
         export RPM_SIGNING_KEY_ID="$RPM_GPG_SIGNING_KEY_ID"
         export NFPM_RPM_PASSPHRASE="$RPM_GPG_SIGNING_PASSPHRASE"
 
-        echo "luaver is $luaver"
         sed -i "s/@luaver@/$luaver/g" ./${{ inputs.nfpm_file_pattern }}
         sed -i "s/@COMMIT_HASH@/${{ inputs.commit_hash }}/g" ./${{ inputs.nfpm_file_pattern }}
         nfpm package --config ./${{ inputs.nfpm_file_pattern }} --packager ${{ inputs.package_extension }}
@@ -81,7 +85,7 @@ runs:
         key: ${{ inputs.cache_key }}
 
     # Update if condition to true to get packages as artifacts
-    - if: ${{ true }}
+    - if: ${{ false }}
       name: Upload package artifacts
       uses: actions/upload-artifact@v3
       with:
