fix: package name and add deb, rpm dependencies

diff --git a/.github/actions/package-nfpm/action.yml b/.github/actions/package-nfpm/action.yml
--- a/.github/actions/package-nfpm/action.yml
+++ b/.github/actions/package-nfpm/action.yml
@@ -60,8 +60,15 @@ runs:
         else
           export DIST=""
         fi
-        MIN_LIB_VERSION="3.0.0"
-        export MIN_LIB_VERSION="$MIN_LIB_VERSION"
+
+        luaver=$(lua -e "print(string.sub(_VERSION, 5))" 2>/dev/null || echo 0)
+        echo "luaver is $luaver"
+        if [ $luaver = "0" ]; then
+          echo "Cannot get lua version"
+          exit 1
+        fi
+
+        export MIN_LIB_VERSION="3.0.0"
         export RPM_SIGNING_KEY_FILE="$(pwd)/key.gpg"
         export RPM_SIGNING_KEY_ID="$RPM_GPG_SIGNING_KEY_ID"
         export NFPM_RPM_PASSPHRASE="$RPM_GPG_SIGNING_PASSPHRASE"
