fix after review

diff --git a/.github/actions/test-packages/action.yml b/.github/actions/test-packages/action.yml
--- a/.github/actions/test-packages/action.yml
+++ b/.github/actions/test-packages/action.yml
@@ -260,7 +260,7 @@ runs:
                   echo "Skip test for $stream_connector (apiv1 stream connector)"
                 else
                   echo "Running test: $stream_connector"
-                  error_output=$(lua "$stream_connector" 2>&1) || { echo "$error_output" >> "$error_log"; echo "Error during $test_script" >> "$error_log"; true; }
+                  error_output=$(lua "$stream_connector" 2>&1) || { echo "$error_output" >> "$error_log"; echo "Error during $stream_connector" >> "$error_log"; true; }
                 fi
               done
               ;;
@@ -317,7 +317,7 @@ runs:
                   echo "Skip test for $stream_connector (apiv1 stream connector)"
                 else
                   echo "Running test: $stream_connector"
-                  error_output=$(lua "$stream_connector" 2>&1) || { echo "$error_output" >> "$error_log"; echo "Error during $test_script" >> "$error_log"; true; }
+                  error_output=$(lua "$stream_connector" 2>&1) || { echo "$error_output" >> "$error_log"; echo "Error during $stream_connector" >> "$error_log"; true; }
                 fi
               done
               ;;
