update for el

diff --git a/.github/actions/test-packages/action.yml b/.github/actions/test-packages/action.yml
--- a/.github/actions/test-packages/action.yml
+++ b/.github/actions/test-packages/action.yml
@@ -254,8 +254,14 @@ runs:
               stream_connectors_dir="/usr/share/centreon-broker/lua"
               for stream_connector in "${stream_connectors_dir}"/*.lua; do
                 [[ -f "$stream_connector" ]] || continue
-                echo "Running test: $stream_connector"
-                error_output=$(lua "$stream_connector" 2>&1) || { echo "$error_output" >> "$error_log"; echo "Error during $test_script" >> "$error_log"; true; }
+                if grep -qE "require \"ndo\"" "$stream_connector"; then
+                  echo "Needs broker runtime, skip test for $stream_connector"
+                elif [[ "$stream_connector" == *apiv1.lua ]]; then
+                  echo "Skip test for $stream_connector (apiv1 stream connector)"
+                else
+                  echo "Running test: $stream_connector"
+                  error_output=$(lua "$stream_connector" 2>&1) || { echo "$error_output" >> "$error_log"; echo "Error during $test_script" >> "$error_log"; true; }
+                fi
               done
               ;;
           esac
